FROM docker.baozou.com/baozou/spark:1.5-py3.4
MAINTAINER XU XIAOMENG <xuxiaomeng@bao.tv>

ENV PIO_VERSION 0.9.4

ENV PIO_HOME /PredictionIO
ENV PATH=${PIO_HOME}/bin:$PATH
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN pip install predictionio

RUN curl -O https://d8k1yxp8elc6b.cloudfront.net/PredictionIO-${PIO_VERSION}.tar.gz
RUN tar -xvzf PredictionIO-${PIO_VERSION}.tar.gz -C /
RUN mv /PredictionIO-${PIO_VERSION} /PredictionIO
RUN rm PredictionIO-${PIO_VERSION}.tar.gz
